# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plan_file', models.FileField(upload_to='./upload/%y/%m/%d/plan_file')),
                ('charger', models.CharField(max_length=20)),
                ('charger_tel', models.CharField(max_length=30)),
                ('activity_member', models.CharField(max_length=500)),
                ('last_time', models.CharField(max_length=100)),
                ('note', models.CharField(max_length=500)),
                ('is_accepted_by_student', models.BooleanField(default=False)),
                ('is_accepted_by_teacher', models.BooleanField(default=False)),
            ],
        ),
    ]
