# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 11:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='activity_date',
            field=models.DateField(default=datetime.datetime(2017, 7, 24, 11, 0, 12, 469999, tzinfo=utc), verbose_name='活动日期'),
        ),
        migrations.AddField(
            model_name='fund',
            name='apply_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 24, 11, 0, 12, 469955, tzinfo=utc), verbose_name='申请日期'),
        ),
    ]
