# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 12:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0002_auto_20170724_1900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fund',
            options={'permissions': (('apply_only', '可以提交申请'), ('student_approve', '学代通道'), ('teacher_approve', '老师通道'))},
        ),
        migrations.AlterField(
            model_name='fund',
            name='activity_date',
            field=models.DateField(default=datetime.datetime(2017, 7, 24, 12, 38, 39, 921327, tzinfo=utc), verbose_name='活动日期'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='apply_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 24, 12, 38, 39, 921297, tzinfo=utc), verbose_name='申请日期'),
        ),
    ]
