# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 10:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0003_auto_20170724_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fund',
            old_name='is_accepted_by_student',
            new_name='is_viewed_by_student',
        ),
        migrations.RenameField(
            model_name='fund',
            old_name='is_accepted_by_teacher',
            new_name='is_viewed_by_teacher',
        ),
        migrations.AddField(
            model_name='fund',
            name='is_objected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fund',
            name='activity_date',
            field=models.DateField(default=datetime.datetime(2017, 7, 26, 10, 43, 26, 74208, tzinfo=utc), verbose_name='活动日期'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='apply_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 26, 10, 43, 26, 74177, tzinfo=utc), verbose_name='申请日期'),
        ),
    ]
