# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-30 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0004_auto_20170726_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='username',
            field=models.CharField(default='exception', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fund',
            name='activity_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='活动日期'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='apply_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='申请日期'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='plan_file',
            field=models.FileField(upload_to='%y/%m/%d/plan_file'),
        ),
    ]
